### ISSUE TITLE
Project description, topics, official etc ?

### ISSUE THREAD

**Issue by Neustradamus** [avahi/nss-mdns#68]
It is possible to add a description, topics, it is official project?

It will be nice to have a link on http://0pointer.de/lennart/projects/nss-mdns/ "0.10"...

**Comment by rworkman** [comment]
@poettering - thoughts?

**Comment by Neustradamus** [comment]
Dear @poettering,

After 5,5yo (6yo soon) and the @rworkman comment, can you check?

Thanks in advance.

**Comment by evverx** [comment]
The link was added to https://avahi.org/ and the announcement was made there. Closing.

**Comment by Neustradamus** [comment]
Dear @avahi team, @evverx: There is nothing in "About" section at right here: https://github.com/avahi/nss-mdns
-> "No description, website, or topics provided."

README is not updated since 25 years old:
- https://github.com/avahi/nss-mdns/blob/master/README.md

I have sent an e-mail to @poettering for this personal website page.

**Comment by Neustradamus** [comment]
Dear @avahi team, @evverx: There is nothing in "About" section at right here: https://github.com/avahi/nss-mdns
-> "No description, website, or topics provided."

README is not updated since 15 years old soon:
- https://github.com/avahi/nss-mdns/blob/master/README.md

I have sent an e-mail to @poettering for this personal website page.
