### ISSUE TITLE
mDNS resolution fails once then succeeds

### ISSUE THREAD

**Issue by toonn** [avahi/nss-mdns#86]
I'm trying to troubleshoot an issue with a machine that fails to resolve mDNS domains.

`avahi-resolve --name yorp.local` seems to always work.
`getent hosts yorp.local` (yorp's the local host name) consistently fails once and then succeeds a number of times. Same behavior with `ping yorp.local`, first an invocation fails, subsequent invocations tend to succeed.

My hypothesis is that the first request actually goes out to the LAN and does eventually get a response but a failure is returned anyway. Then subsequent requests succeed because they hit some sort of cache. Until that cache entry is cleared.

I ran a loop to test this hypothesis.

```
> for i in (seq 100); printf '%d: ' "$i"; getent hosts yorp.local || printf '\n'; sleep 10; end
1: 
2: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
3: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
4: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
5: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
6: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
7: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
8: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
9: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
10: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
11: 
12: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
13: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
14: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
15: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
16: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
17: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
18: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
19: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
20: 
21: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
22: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
23: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
24: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
25: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
26: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
27: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
28: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
29: 
30: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
31: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
32: ::1             yorp.local
33: ::1             yorp.local
34: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
35: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
36: 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3 yorp.local
37: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
38: 
39: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
40: 2a02:1810:4480:fe00:41c1:c941:e6ca:4df yorp.local
```

It does look like every ~9 iterations, so every minute and a half, the `getent` query times out. I'm not sure why the resolved address sometimes differs though. Maybe it is doing queries after all and my host sends all of those answers and sometimes they arrive in different orders? That doesn't explain the time outs though.

All three of those addresses are valid for my wired connection. `::1` is the default loopback address IIUC. I'm not entirely sure what the other two are but I think there may be two due to privacy extensions or something? The properties do differ.

```
    inet6 2a02:1810:4480:fe00:41c1:c941:e6ca:4df/64 scope global temporary dynamic 
    inet6 2a02:1810:4480:fe00:bb6b:d829:8b54:a7c3/64 scope global dynamic mngtmpaddr noprefixroute
```

Potentially relevant config files:

I've been testing things, normally I use `mdns4` instead of `mdns_minimal` because I use subdomains.
```
~> cat /etc/nsswitch.conf
passwd:    files systemd
group:     files systemd
shadow:    files

hosts:     mymachines files myhostname mdns_minimal [NOTFOUND=return] dns
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

`avahi-daemon` is run with the following configuration passed in using the `-f` flag.

```
~> cat /nix/store/7wn5q6dakf56lidd0vzh6hw2rw74yxrz-avahi-daemon.conf
[server]
host-name=yorp
browse-domains=
use-ipv4=yes
use-ipv6=no

domain-name=local
allow-point-to-point=no


[wide-area]
enable-wide-area=yes

[publish]
disable-publishing=no
disable-user-service-publishing=no
publish-addresses=yes
publish-hinfo=no
publish-workstation=no
publish-domain=no

[reflector]
enable-reflector=no
```

**Comment by toonn** [comment]
When testing with `mdns4` or `mdns4_minimal` the loop simply never returned an IP, each iteration timed out.
I'm not sure why but `ping` always kept showing the same behavior of timing out once and then working fine for a bit, with both `mdns4` and `mdns4_minimal` set.

**Comment by hifron** [comment]
today is also systemd-networking and I could not imagine why router does not tell that they are this devices on network and which services are open from local network.

Direct messaging between devices are possible if desired, but not in default environment. And if avahi with systemd reach agreement, maybe GNOME will join this crazy enterprise...

**Comment by toonn** [comment]
Closing this issue because I think the cause was a failing `nscd.service`.

**Comment by dolezaljan** [comment]
another workaround using `systemd-resolved` service:

`/etc/systemd/resolved.conf`
```
MulticastDNS=yes
```

`/etc/nsswitch.conf`
```
hosts:          files resolve [NOTFOUND=return] dns
```

run:
```
systemctl daemon-reload
systemctl restart systemd-resolved.service
```

**Comment by hifron** [comment]
There should be list from router, not from multicast. But such router info package(where is router) for systemd is not on the accepted list in debian, not alone(with a lot of dns system problems, there is a _missing|theory_ about).

_But getting priority on streaming is also possible(with multicast), but network filtering(as next on the list) is also more advanced domain._

Multicast enabled is therefore not so easy to check how to address this problem, but often it could be denied, maybe networks with IPv6 and 4 need more default healthy policies to be enabled to prevent some health damages and MultcastDNS to off is one of them.

networker people are today not without some health injury mental illness pills, networking is hard and Debian or systemd is full of manual options with ants do their management without people's involvement to do their Desktop/Network jobs.
