### ISSUE TITLE
Transfer this repository to avahi-project GitHub organization

### ISSUE THREAD

**Issue by Neustradamus** [avahi/nss-mdns#92]
Dear nss-mdns team, @lathiat, @agoode,

Any progress for the transfer of this avahi repository (https://github.com/lathiat/avahi) and nss-mdns repository (https://github.com/lathiat/nss-mdns) to avahi-project GitHub organization that I have created to have a best future, a best development, new releases?
Note: I have not rights now.

I think that @agoode must to be in the avahi-project GitHub organization (if it is not yet).

Badly, at this time, a lot of people think that it is a dead project like Avahi and maybe unsecure like Avahi.
- https://github.com/lathiat/nss-mdns/issues/85
- https://github.com/lathiat/avahi/issues/325
- https://github.com/lathiat/avahi/issues/430
- https://github.com/lathiat/avahi/issues/503

Some projects have been blocked at an old place because the "original" repository can not be transfered because a death, away dev, ...

For example:
- https://github.com/glennrp

Thanks in advance.

**Comment by Neustradamus** [comment]
@evverx: Excellent, several years after my original request!

Dear @avahi team, it is possible to edit here:
- https://github.com/avahi-project

Replace the subject and specify that the project is here: https://github.com/avahi and the link too?

**Comment by evverx** [comment]
I think that organization should be just removed but I don't know who has that kind of access. Either way I don't think that that organization has anything to do with this issue. https://avahi.org/ says where the official organization is.

**Comment by Neustradamus** [comment]
@lathiat has possibility...

The website is now hosted here:
- https://github.com/avahi/avahi.github.io

Now you can look to have verified avahi.org:
- https://github.com/organizations/avahi/settings/domains

**Comment by evverx** [comment]
I don't think that organization matters much. Anyone can create a gazillion organization pointing to the site.

> Now you can look to have verified avahi.org

I agree it would be great to verify the domain, provide signed tarballs, protect branches and so on (and I get where all those requests come from) but those are separate issues and they should be tracked separately. I think this particular issue is resolved because the organization has been created and the repositories have been moved.

**Comment by lathiat** [comment]
I have access to the old one and will delete it

FYI: the avahi.github.io repository is created but not yet live.

**Comment by lathiat** [comment]
Have deleted avahi-zeroconf and avahi-project
